### ISSUE TITLE
'Sequential' object has no attribute '_layers' in Mac M1

### ISSUE THREAD

**Issue by chinmayaNK22** [bzhanglab/AutoRT#12]
Hello,

I am trying to train a model using autort in my Mac M1 laptop, it ends up with an error (Please find the output with an error below).

The same works perfectly in NVIDIA graphic card in other windows systems with Tensorflow GPU.

What could be the issue here in Mac? How can I solve it?

Please let me know if you have any solutions?

```
Init Plugin
Init Graph Optimizer
Init Kernel
Scaling method: min_max
New aa: 1 -> 20
New aa: 2 -> 21
New aa: 3 -> 22
Save aa coding data to file ../../Mavium_Proteomics/omics/Mavium_proteome_search_model/aa.tsv
AA types: 23
Longest peptide in training data: 49

['1', '2', '3', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y']
RT range: 0 - 112

X_train shape:
(19539, 49, 23)
X_test shape:
(2171, 49, 23)
Modeling start ...
max_x_length: 48
Model file: 0 -> models/base_models/model_0.json
Metal device set to: Apple M1

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB

2021-09-01 19:14:28.313930: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2021-09-01 19:14:28.314052: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
Traceback (most recent call last):
  File "/Users/chinmayanarayana/Desktop/Yenepoya/Prediction_Tools/AutoRT-master/autort.py", line 133, in <module>
    main()
  File "/Users/chinmayanarayana/Desktop/Yenepoya/Prediction_Tools/AutoRT-master/autort.py", line 95, in main
    ensemble_models(input_data=input_file, nb_epoch=epochs, batch_size=batch_size,
  File "/Users/chinmayanarayana/Desktop/Yenepoya/Prediction_Tools/AutoRT-master/autort/RTModels.py", line 351, in ensemble_models
    models[i]._layers[0]._batch_input_shape = (None, X_train.shape[1], X_train.shape[2])
AttributeError: 'Sequential' object has no attribute '_layers'
```
Thank you,
Chinmaya

**Comment by wenbostar** [comment]
It looks like the TensorFlow version you used in Mac is not compatible with AutoRT. Which version of TensorFlow are you using in the Mac?

**Comment by chinmayaNK22** [comment]
The tensorflow version in my system is 2.5. Which is what AutoRT requires right?

```
(tensorflow) chinmayanarayana@Chinmayas-MacBook-Pro ~ % python -c 'import tensorflow as tf; print(tf.__version__)'
Init Plugin
Init Graph Optimizer
Init Kernel
2.5.0
```

**Comment by wenbostar** [comment]
Could you send me the command line for training you used？

**Comment by chinmayaNK22** [comment]
Below is the command line for training.

```
(tensorflow) chinmayanarayana@Chinmayas-MacBook-Pro AutoRT-master % python autort.py train -e 100 -b 64 -g models/base_models/model.json -u m -p 1,2,3 -i ../../NTNU_Mavium_Proteomics/Proteogenomics/M_avium_Mavium_hominissuis_proteome_search_081821_PeptideGroups_autort_input.tsv -sm min_max -l 48 -rlr -n 20 -o ../../NTNU_Mavium_Proteomics/Mavium_hominissuis_proteome_search_model
```
The output

```
Init Plugin
Init Graph Optimizer
Init Kernel
Scaling method: min_max
New aa: 1 -> 20
New aa: 2 -> 21
New aa: 3 -> 22
Save aa coding data to file ../../NTNU_Mavium_Proteomics/Mavium_hominissuis_proteome_search_model/aa.tsv
AA types: 23
Longest peptide in training data: 49

['1', '2', '3', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y']
RT range: 0 - 112

X_train shape:
(19539, 49, 23)
X_test shape:
(2171, 49, 23)
Modeling start ...
max_x_length: 48
Model file: 0 -> models/base_models/model_0.json
Metal device set to: Apple M1

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB

2021-09-01 21:46:16.353766: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2021-09-01 21:46:16.353852: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
Traceback (most recent call last):
  File "/Users/chinmayanarayana/Desktop/Yenepoya/Prediction_Tools/AutoRT-master/autort.py", line 133, in <module>
    main()
  File "/Users/chinmayanarayana/Desktop/Yenepoya/Prediction_Tools/AutoRT-master/autort.py", line 95, in main
    ensemble_models(input_data=input_file, nb_epoch=epochs, batch_size=batch_size,
  File "/Users/chinmayanarayana/Desktop/Yenepoya/Prediction_Tools/AutoRT-master/autort/RTModels.py", line 351, in ensemble_models
    models[i]._layers[0]._batch_input_shape = (None, X_train.shape[1], X_train.shape[2])
AttributeError: 'Sequential' object has no attribute '_layers'
(tensorflow) chinmayanarayana@Chinmayas-MacBook-Pro AutoRT-master % 
```

**Comment by gusye1234** [comment]
I had the same error too. 
I'm using the docker this repo provide `proteomics/autort`/
