### ISSUE TITLE
Running AutoRT on Windows

### ISSUE THREAD

**Issue by WinkelsK** [bzhanglab/AutoRT#14]
Hey all - I just downloaded AutoRT. It sounds like its exactly what I want :)
Unfortunately I wasn't able to run the example files. It comes up with the following error.
As I don't have much experience in Python, I am looking forward to your input! Thanks!

```
(base) C:\AutoRT_master\AutoRT_master\example>python ../autort.py train -i data/
28CPTAC_COprospective_W_VU_20150810_05CO037_f01_normal_train.tsv -o tf_model/ -e
 40 -b 64 -u m -m ../models/general_base_model/model.json -rlr -n 10
2021-10-19 13:33:43.548612: W tensorflow/stream_executor/platform/default/dso_lo
ader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64
_110.dll not found
2021-10-19 13:33:43.558612: I tensorflow/stream_executor/cuda/cudart_stub.cc:29]
 Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Scaling method: min_max
Step 1:

Load aa coding data from file ../models/general_base_model/aa.tsv
AA types: 25
Longest peptide in training data: 41

Use test file tf_model//step1/validation.tsv
Longest peptide in test data: 30

['1', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'P', 'Q', 'R',
 'S', 'T', 'V', 'W', 'Y']
RT range: 0 - 98

X_train shape:
(4626, 60)
X_test shape:
(515, 60)
Modeling start ...
Use one GPU or no GPU!
2021-10-19 13:33:47.248617: W tensorflow/stream_executor/platform/default/dso_lo
ader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64
_110.dll not found
2021-10-19 13:33:47.248617: I tensorflow/stream_executor/cuda/cudart_stub.cc:29]
 Ignore above cudart dlerror if you do not have a GPU set up on your machine.

Model training: 0
2021-10-19 13:33:50.828622: W tensorflow/stream_executor/platform/default/dso_lo
ader.cc:64] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not
 found
2021-10-19 13:33:50.838622: W tensorflow/stream_executor/cuda/cuda_driver.cc:269
] failed call to cuInit: UNKNOWN ERROR (303)
2021-10-19 13:33:50.848622: I tensorflow/stream_executor/cuda/cuda_diagnostics.c
c:169] retrieving CUDA diagnostic information for host: MININT-L73FV72
2021-10-19 13:33:50.848622: I tensorflow/stream_executor/cuda/cuda_diagnostics.c
c:176] hostname: MININT-L73FV72
2021-10-19 13:33:50.848622: I tensorflow/core/platform/cpu_feature_guard.cc:142]
 This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (on
eDNN) to use the following CPU instructions in performance-critical operations:
 AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate comp
iler flags.
60
Perform transfer learning ...
The number of layers: 11
<keras.optimizer_v2.adam.Adam object at 0x0000000050193FA0>
Use optimizer: Adam from saved model
Used optimizer:
<keras.optimizer_v2.adam.Adam object at 0x000000005018AD00>
Batch size: 64
Epoch: 40
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 125, in work
er
    result = (True, func(*args, **kwds))
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 48, in mapst
ar
    return list(map(*args))
  File "C:\AutoRT_master\AutoRT_master\autort\ModelT.py", line 14, in run_model_
t
    model_t.run()
  File "C:\AutoRT_master\AutoRT_master\autort\ModelT.py", line 153, in run
    new_model.fit(ModelT.x_train, ModelT.y_train, batch_size=ModelT.batch_size,
epochs=ModelT.n_epoch,
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", li
ne 1134, in fit
    data_handler = data_adapter.get_data_handler(
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\data_adapter.py"
, line 1383, in get_data_handler
    return DataHandler(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\data_adapter.py"
, line 1137, in __init__
    adapter_cls = select_data_adapter(x, y)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\data_adapter.py"
, line 976, in select_data_adapter
    raise ValueError(
ValueError: Failed to find data adapter that can handle input: <class 'NoneType'
>, <class 'NoneType'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "../autort.py", line 158, in <module>
    main()
  File "../autort.py", line 109, in main
    two_step_ensemble_models(input_data=input_file, nb_epoch=epochs, batch_size=
batch_size,
  File "C:\AutoRT_master\AutoRT_master\autort\RTModels.py", line 675, in two_ste
p_ensemble_models
    ensemble_models(models_file=models_file, input_data=input_data, ensemble_met
hod=ensemble_method,
  File "C:\AutoRT_master\AutoRT_master\autort\RTModels.py", line 814, in ensembl
e_models
    trained_model = p.map(run_model_t, [model_t])
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 125, in work
er
    result = (True, func(*args, **kwds))
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 48, in mapst
ar
    return list(map(*args))
  File "C:\AutoRT_master\AutoRT_master\autort\ModelT.py", line 14, in run_model_
t
    model_t.run()
  File "C:\AutoRT_master\AutoRT_master\autort\ModelT.py", line 153, in run
    new_model.fit(ModelT.x_train, ModelT.y_train, batch_size=ModelT.batch_size,
epochs=ModelT.n_epoch,
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", li
ne 1134, in fit
    data_handler = data_adapter.get_data_handler(
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\data_adapter.py"
, line 1383, in get_data_handler
    return DataHandler(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\data_adapter.py"
, line 1137, in __init__
    adapter_cls = select_data_adapter(x, y)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\data_adapter.py"
, line 976, in select_data_adapter
    raise ValueError(
ValueError: Failed to find data adapter that can handle input: <class 'NoneType'
>, <class 'NoneType'>

(base) C:\AutoRT_master\AutoRT_master\example>

**Comment by wenbostar** [comment]
Could you run AutoRT example again?

**Comment by WinkelsK** [comment]
Great - it is running now! Thanks!

**Comment by hetaofan** [comment]
Hello, I want to predict RT under Windows, but I am new and don't know what to do? Now I have peptide sequence and modification. How should I make RT predictions? Thank you for your help

**Comment by wenbostar** [comment]
@hetaofan , could you open a new issue about your question?
