### ISSUE TITLE
How can I get RT 

### ISSUE THREAD

**Issue by hetaofan** [bzhanglab/AutoRT#21]
Hello, I want to predict RT under Windows, but I am new and don't know what to do? Now I have peptide sequence and modification. How should I make RT predictions? Thank you for your help

**Comment by wenbostar** [comment]
A good start is to use Google Colab: https://github.com/bzhanglab/AutoRT/blob/master/example/Experiment_specific_RT_prediction_using_AutoRT.ipynb. You could run both model training and prediction using Colab in your web browser.

**Comment by hetaofan** [comment]
Ok. I will read it thanks for fast reply

**Comment by wenbostar** [comment]
Did you run the analysis from the beginning? If not, you should run the analysis from the beginning of the notebook. For the format issue, you could find description about that at https://github.com/bzhanglab/AutoRT#usage.

**Comment by wenbostar** [comment]
> Can I run it on windows environment?

Yes, AutoRT can be run on Windows system. The usage is almost the same. For installation, you can follow the description at https://github.com/bzhanglab/AutoRT#installation.

**Comment by hetaofan** [comment]
thanks for your reply. I will study it

**Comment by hetaofan** [comment]
Hello wenbostar. When I run the trainning part: ! python ../autort.py train -i data/28CPTAC_COprospective_W_VU_20150810_05CO037_f01_normal_train.tsv -o tf_model/ -e 40 -b 64
I gte error like this:
2023-06-12 07:10:58.717982: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-12 07:10:59.749707: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Scaling method: min_max
Step 1:

Traceback (most recent call last):
  File "/content/AutoRT/example/../autort.py", line 160, in <module>
    main()
  File "/content/AutoRT/example/../autort.py", line 110, in main
    two_step_ensemble_models(input_data=input_file, nb_epoch=epochs, batch_size=batch_size,
  File "/content/AutoRT/autort/RTModels.py", line 677, in two_step_ensemble_models
    trained_model_file = ensemble_models(models_file=models_file, input_data=input_data, ensemble_method=ensemble_method,
  File "/content/AutoRT/autort/RTModels.py", line 739, in ensemble_models
    with open(models_file, "r") as read_file:
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by hetaofan** [comment]
I have two modifications(Oxidation and Carbamidomethy) so I think maybe I need to rebuild a mode? Or can I use  pre-trained models with transfer learning .

**Comment by wenbostar** [comment]
You can use pre-trained model with transfer learning.

**Comment by hetaofan** [comment]
Would you please tell me how to do ?I'm confused┭┮﹏┭┮

**Comment by wenbostar** [comment]
Yes, you could follow this tutorial: https://github.com/bzhanglab/AutoRT/blob/master/example/Experiment_specific_RT_prediction_using_AutoRT.ipynb
